name: Publish DotnetDevkit.Cache.Abstractions

on:
  push:
    tags:
      - 'cache/v*'

jobs:
  publish:
    uses: ./.github/workflows/nuget-publish-template.yml
    with:
      project-path: 'src/Cache/DotnetDevkit.Cache.Abstractions/DotnetDevkit.Cache.Abstractions.csproj'
      tag-prefix: 'cache/v'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
